// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: catalog/v1/catalog_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_catalog_v1_catalog_service_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_service_proto_rawDesc = "" +
	"\n" +
	" catalog/v1/catalog_service.proto\x12\n" +
	"catalog.v1\x1a\x18catalog/v1/product.proto\x1a\x19catalog/v1/category.proto2\xad\x03\n" +
	"\x0eCatalogService\x12T\n" +
	"\rCreateProduct\x12 .catalog.v1.CreateProductRequest\x1a!.catalog.v1.CreateProductResponse\x12@\n" +
	"\n" +
	"GetProduct\x12\x1d.catalog.v1.GetProductRequest\x1a\x13.catalog.v1.Product\x12Q\n" +
	"\fListProducts\x12\x1f.catalog.v1.ListProductsRequest\x1a .catalog.v1.ListProductsResponse\x12W\n" +
	"\x0eCreateCategory\x12!.catalog.v1.CreateCategoryRequest\x1a\".catalog.v1.CreateCategoryResponse\x12W\n" +
	"\x0eListCategories\x12!.catalog.v1.ListCategoriesRequest\x1a\".catalog.v1.ListCategoriesResponseB\x0fZ\rcatalog/v1;v1b\x06proto3"

var file_catalog_v1_catalog_service_proto_goTypes = []any{
	(*CreateProductRequest)(nil),   // 0: catalog.v1.CreateProductRequest
	(*GetProductRequest)(nil),      // 1: catalog.v1.GetProductRequest
	(*ListProductsRequest)(nil),    // 2: catalog.v1.ListProductsRequest
	(*CreateCategoryRequest)(nil),  // 3: catalog.v1.CreateCategoryRequest
	(*ListCategoriesRequest)(nil),  // 4: catalog.v1.ListCategoriesRequest
	(*CreateProductResponse)(nil),  // 5: catalog.v1.CreateProductResponse
	(*Product)(nil),                // 6: catalog.v1.Product
	(*ListProductsResponse)(nil),   // 7: catalog.v1.ListProductsResponse
	(*CreateCategoryResponse)(nil), // 8: catalog.v1.CreateCategoryResponse
	(*ListCategoriesResponse)(nil), // 9: catalog.v1.ListCategoriesResponse
}
var file_catalog_v1_catalog_service_proto_depIdxs = []int32{
	0, // 0: catalog.v1.CatalogService.CreateProduct:input_type -> catalog.v1.CreateProductRequest
	1, // 1: catalog.v1.CatalogService.GetProduct:input_type -> catalog.v1.GetProductRequest
	2, // 2: catalog.v1.CatalogService.ListProducts:input_type -> catalog.v1.ListProductsRequest
	3, // 3: catalog.v1.CatalogService.CreateCategory:input_type -> catalog.v1.CreateCategoryRequest
	4, // 4: catalog.v1.CatalogService.ListCategories:input_type -> catalog.v1.ListCategoriesRequest
	5, // 5: catalog.v1.CatalogService.CreateProduct:output_type -> catalog.v1.CreateProductResponse
	6, // 6: catalog.v1.CatalogService.GetProduct:output_type -> catalog.v1.Product
	7, // 7: catalog.v1.CatalogService.ListProducts:output_type -> catalog.v1.ListProductsResponse
	8, // 8: catalog.v1.CatalogService.CreateCategory:output_type -> catalog.v1.CreateCategoryResponse
	9, // 9: catalog.v1.CatalogService.ListCategories:output_type -> catalog.v1.ListCategoriesResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_service_proto_init() }
func file_catalog_v1_catalog_service_proto_init() {
	if File_catalog_v1_catalog_service_proto != nil {
		return
	}
	file_catalog_v1_product_proto_init()
	file_catalog_v1_category_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_service_proto_rawDesc), len(file_catalog_v1_catalog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_service_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_service_proto_depIdxs,
	}.Build()
	File_catalog_v1_catalog_service_proto = out.File
	file_catalog_v1_catalog_service_proto_goTypes = nil
	file_catalog_v1_catalog_service_proto_depIdxs = nil
}
