// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	ImageURL *string `json:"image_url,omitempty"`
	ParentID *string `json:"parent_id,omitempty"`
	Depth    int32   `json:"depth"`
}

type CreateCategoryInput struct {
	Name     string  `json:"name"`
	ImageURL *string `json:"image_url,omitempty"`
	ParentID *string `json:"parent_id,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
