# docker run --name black-shop-mongo -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=omides248 -e MONGO_INITDB_ROOT_PASSWORD=123123 -d mongo
# docker run --name black-shop-postgres -p 5432:5432 -e POSTGRES_USER=omides248 -e POSTGRES_PASSWORD=123123 -e POSTGRES_DB=identity_db -d postgres
# docker run --name black-shop-redis -p 6379:6379 -d redis

services:
  mongo:
    image: mongo
    container_name: black-shop-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=omides248
      - MONGO_INITDB_ROOT_PASSWORD=123123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.75"

  postgres:
    image: postgres
    container_name: black-shop-postgres
    environment:
      - POSTGRES_USER=omides248
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgresql.sh:/docker-entrypoint-initdb.d/init-db.sh
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  redis:
    image: redis
    container_name: black-shop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

#  minio:
#    image: minio/minio
#    container_name: black-shop-minio
#    command: server /data --console-address ":9001"
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - minio-data:/data
#    deploy:
#      resources:
#        limits:
#          memory: 512M
#          cpus: "0.5"


volumes:
  mongo-data:
  postgres-data:
  redis-data:
  minio-data:




#services:
#  mongo:
#    image: mongo
#    container_name: black-shop-mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=omides248
#      - MONGO_INITDB_ROOT_PASSWORD=123123
#    ports:
#      - "27017:27017"
#    command: ["--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo-keyfile"]
#    volumes:
#      - mongo-data:/data/db
#      - ./mongo-keyfile:/etc/mongo-keyfile:ro
#
#  postgres:
#    image: postgres
#    container_name: black-shop-postgres
#    environment:
#      - POSTGRES_USER=omides248
#      - POSTGRES_PASSWORD=123123
#      - POSTGRES_DB=identity_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#      - ./init-postgresql.sh:/docker-entrypoint-initdb.d/init-db.sh
#
#  redis:
#    image: redis
#    container_name: black-shop-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#
#volumes:
#  mongo-data:
#  postgres-data:
#  redis-data:
